apps/menus/urls.py
# Django
from django.urls import path

# Apps.menus
from apps.menus import views

app_name='menus'

urlpatterns = [
    path('add/ingredient', views.create_ingredient, name='add-ingredient'),
    path('list/ingredient', views.list_ingredient, name='list-ingredient'),

    path('add/menu', views.create_menu, name='add-menu'),
    path('list/menu', views.list_menu, name='list-menu'),

    path('list/plate/<int:pk_menu>', views.list_plate_from_menu, name='list-plate-from-menu'),
    path('add/ingredient_to_plate/<int:pk_menu>/<str:type_plate>',
         views.add_ingredient_to_plate,
         name='add-ingredient-to-plate'),
]

mi_cornershop/urls.py
#Django
from django.contrib import admin
from django.urls import path, include

#Project
from mi_cornershop import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('users/login', views.login_custom, name='login'),
    path('users/logout', views.logout_custom, name='logout'),
    path('menus/', include('apps.menus.urls')),
    path('employees/', include('apps.employees.urls')),
]

apps/menus/models.py
# Django and Python
import uuid
from datetime import datetime
from django.db import models
from django.db.models.signals import pre_save

class Ingredient(models.Model):
    type_options = (
        ('1', 'Simple'),
        ('2', 'Prepared'),
    )
    name = models.CharField(max_length=100, null=False, default='')
    type = models.CharField(max_length=1, choices=type_options, default='1')
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Plate(models.Model):
    type_options = (
        ('1', 'Lunch'),
        ('2', 'Salad'),
        ('3', 'Dessert'),
    )
    name = models.CharField(max_length=100, null=False, default='')
    type = models.CharField(max_length=1, choices=type_options, default='1')
    ingredients = models.ManyToManyField(Ingredient, through='PlateIngredients')
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.get_type_display()

class Menu(models.Model):
    name = models.CharField(max_length=100, null=False, default='')
    day = models.DateTimeField(default=datetime.now, blank=False)
    identifier = models.CharField(max_length=100, null=False, blank=False, unique=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.identifier

    def get_or_create_plate(self, type_plate):
        """

        :param type_plate (string):
        :return (Plate):
        """
        if not PlateIngredients.objects.filter(menu=self, plate__type=type_plate).count():
            return Plate.objects.create(name=' ', type=type_plate)
        else:
            return PlateIngredients.objects.filter(menu=self, plate__type=type_plate).first().plate

class PlateIngredients(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    plate = models.ForeignKey(Plate, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['plate', 'ingredient']]

def set_menu_identifier(sender, instance, *args, **kwargs):
    """
    Function that help me to create diffucult ID for the menu instance
    :param sender (Class): Menu class
    :param instance (Object): Menu instace
    :param args (list): other paramethers
    :param kwargs (list): other paramethers
    :return (None):
    """
    #valid if menu has id
    if not instance.identifier:
        #add strong id
        instance.identifier = str(uuid.uuid4())

#I notific that before create menu new, must pass for particular function
pre_save.connect(set_menu_identifier, sender=Menu)

"""
Tips to load data: 

** You can use this command for load data 
$ python3 manage.py loaddata ingredients_03112020.json
"""

apps/menus/forms.py
# Django
from django import forms

# Apps.menus
from apps.menus import models

class IngredientForm(forms.ModelForm):
    class Meta:
        model = models.Ingredient
        exclude = ('create_at', )
        fields = ('name', 'type',)
        labels = {
            'name' : 'Name',
            'type' : 'Type',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
        }

class MenuForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        exclude = ('menu_id', 'create_at', )
        fields = ('name', 'day',)
        labels = {
            'name' : 'Name',
            'day' : 'Publication date',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'day': forms.DateTimeInput(attrs={'class': 'form-control', 'type':'date'}),
        }

class PlateIngredientsForm(forms.ModelForm):
    class Meta:
        model = models.PlateIngredients
        exclude = ('create_at', )
        fields = ('menu', 'plate', 'ingredient',)
        labels = {
            'menu' : '',
            'plate' : '',
            'ingredient' : 'Ingredient'
        }
        widgets = {
            'menu': forms.HiddenInput(),
            'plate': forms.HiddenInput(),
            'ingredient': forms.Select(attrs={'class': 'form-control'}),
        }
        error_messages = {
            '__all__': {
                'unique_together': "This ingredient already exists in this plate.",
            }
        }

apps/menus/views.py
# Django
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Apps.menus
from apps.menus import forms
from apps.menus import models

@login_required()
def create_ingredient(request):
    """
    Function to create ingredients
    :param request (POST):
    :return ():
    """

    data = dict()

    if request.method == 'POST':
        form = forms.IngredientForm(request.POST)

        if form.is_valid():
            form.save()

            # I send a success message
            messages.success(request, 'Ingredient was create successful')

            return redirect('menus:list-ingredient')
    else:
        form = forms.IngredientForm()

    data['form'] = form
    data['title'] = 'Add Ingredient'

    return render(request, 'menus/ingredient/add_ingredient.html', data)

@login_required()
def list_ingredient(request):
    """
    Function for lists the ingredients
    :param request (POST):
    :return ():
    """

    data = dict()
    data['list_ingredients'] = models.Ingredient.objects.all()
    data['title'] = 'Ingredient List'

    return render(request, 'menus/ingredient/list_ingredient.html', data)

@login_required()
def create_menu(request):
    """
    Function to create ingredients with particular date
    :param request:
    :return:
    """
    data = dict()

    if request.method == 'POST':
        form = forms.MenuForm(request.POST)

        if form.is_valid():
            form.save()

            # I send a success message
            messages.success(request, 'Menu was create successful')

            return redirect('menus:list-menu')
    else:
        form = forms.MenuForm()
        tomorrow = datetime.now() + timedelta(days=1)
        tomorrow_formatted = tomorrow.strftime('%Y-%m-%d')
        form.fields['day'].initial = tomorrow_formatted

    data['form'] = form
    data['title'] = ' Menu'

    return render(request, 'menus/menu/add_menu.html', data)

@login_required()
def list_menu(request):
    """
    Function for lists the menus
    :param request ():
    :return ():
    """

    data = dict()
    data['list_menus'] = models.Menu.objects.all()
    data['title'] = 'Menu List'

    return render(request, 'menus/menu/list_menu.html', data)

@login_required()
def list_plate_from_menu(request, pk_menu):
    """

    :param request ():
    :param pk_menu (int):
    :return:
    """

    data = dict()

    my_plates = models.PlateIngredients.objects.filter(menu=pk_menu)
    data['my_plates_lunch'] = my_plates.filter(plate__type='1')
    data['my_plates_salad'] = my_plates.filter(plate__type='2')
    data['my_plates_dessert'] = my_plates.filter(plate__type='3')

    data['title'] = "Menu's plates"
    data['pk_menu'] = pk_menu

    return render(request, 'menus/plate/list_plate_from_menu.html', data)

@login_required()
def add_ingredient_to_plate(request, pk_menu, type_plate):
    """

    :param request ():
    :param pk_menu (int):
    :param type_plate (string):
    :return:
    """

    data = dict()

    if request.method == 'POST':
        form = forms.PlateIngredientsForm(request.POST)

        if form.is_valid():
            form.save()

            # I send a success message
            messages.success(request, 'Ingredient was add to the plate')

            return redirect('menus:list-plate-from-menu', pk_menu)
    else:
        form = forms.PlateIngredientsForm()

        if models.Menu.objects.filter(pk=pk_menu).exists():
            my_menu = models.Menu.objects.get(pk=pk_menu)
            form.fields['menu'].initial = my_menu
            my_plate = my_menu.get_or_create_plate(type_plate)
            form.fields['plate'].initial = my_plate
        else:
            return redirect('menus:list-menu')

    data['form'] = form
    data['title'] = 'Add ingredient to plate'
    data['pk_menu'] = pk_menu
    data['type_plate'] = type_plate

    return render(request, 'menus/plate/add_ingredient_to_plate.html', data)

apps/menus/templates/menus/plate/add_ingredient_to_plate.html
{% extends 'base.html' %}

{% block content %}
    {% url 'menus:list-plate-from-menu' pk_menu as back_to_menu %}
    {% url 'menus:list-plate-from-menu' pk_menu type_plate as add_ingredient %}

    <div class="row">
        <div class="col-lg-1 col-lg-offset-11">
            <a href="{{back_to_menu}}" class="btn btn-info">Back</a>
        </div>
        <div class="col-lg-12">
            <form method="post" id="id_form" name="form" action="{{add_ingredient}}">
                <div class="form-group">
                    {% csrf_token %}
                    {{form.as_table}}
                </div>
                <div class="form-group">
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button type="submit" class="btn btn-success" id="id_btn_add" name="btn_add">Add</button>
                </div>
            </form>
        </div>
    </div>
{% endblock%}

apps/menus/templates/menus/plate/list_plate_from_menu.html
{% extends 'base.html' %}

{% block content %}
    {% url 'menus:list-menu' as list_menu %}
    {% url 'home' as home %}

    <div class="row">
        <div class="col-lg-3 col-lg-offset-9">
            <a href="{{list_menu}}" class="btn btn-info">Back</a>
        </div>

        <div class="col-lg-6">
            <div class="row">
                <div class="col-lg-4"><h3 style="margin-top: 0px;">Lunch</h3></div>
                <div class="col-lg-4 col-lg-offset-4"><a href="{% url 'menus:add-ingredient-to-plate' pk_menu '1' %}" class="btn btn-primary">Add Ingredient</a></div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Ingredient</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pi in my_plates_lunch %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ pi.ingredient.name|capfirst }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="2">without ingredients</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-lg-6">
            <div class="row">
                <div class="col-lg-4"><h3 style="margin-top: 0px;">Salad</h3></div>
                <div class="col-lg-4 col-lg-offset-4"><a href="{% url 'menus:add-ingredient-to-plate' pk_menu '2' %}" class="btn btn-primary">Add Ingredient</a></div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Ingredient</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pi in my_plates_salad %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ pi.ingredient.name|capfirst }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="2">without ingredients</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-lg-6">
            <div class="row">
                <div class="col-lg-4"><h3 style="margin-top: 0px;">Dessert</h3></div>
                <div class="col-lg-4 col-lg-offset-4"><a href="{% url 'menus:add-ingredient-to-plate' pk_menu '3' %}" class="btn btn-primary">Add Ingredient</a></div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Ingredient</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pi in my_plates_dessert %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ pi.ingredient.name|capfirst }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="2">without ingredients</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock%}