apps/employees/urls.py
# Django
from django.urls import path

# Apps.Employees
from apps.employees import views

app_name='employees'

urlpatterns = [
    path('search/', views.search_employee, name='search-employee'),
    path('list/menu/<int:phone>', views.list_menu, name='list-menu'),
    path('list/plate/<str:identifier>/<int:phone>', views.list_plate_from_menu, name='list-plate-from-menu'),
    path('add/preference/<str:identifier>/<int:phone>/<str:type_plate>', views.add_preference_of_employee, name='add-preference-of-employee'),
]

apps/menus/urls.py
# Django
from django.urls import path

# Apps.menus
from apps.menus import views

app_name='menus'

urlpatterns = [
    path('add/ingredient', views.create_ingredient, name='add-ingredient'),
    path('list/ingredient', views.list_ingredient, name='list-ingredient'),

    path('add/menu', views.create_menu, name='add-menu'),
    path('list/menu', views.list_menu, name='list-menu'),

    path('list/plate/<int:pk_menu>', views.list_plate_from_menu, name='list-plate-from-menu'),
    path('add/ingredient_to_plate/<int:pk_menu>/<str:type_plate>',
         views.add_ingredient_to_plate,
         name='add-ingredient-to-plate'),
]

mi_cornershop/urls.py
#Django
from django.contrib import admin
from django.urls import path, include

#Project
from mi_cornershop import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('users/login', views.login_custom, name='login'),
    path('users/logout', views.logout_custom, name='logout'),
    path('menus/', include('apps.menus.urls')),
    path('employees/', include('apps.employees.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{title}}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        {% block my_css %}{% endblock %}
    </head>
    <body>
        {% include 'nav.html' %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% include 'messages.html' %}
                </div>
            </div>
            {# aca se concetra el contenido de cada pagina#}
            {% block content %}{% endblock %}
        </div>
        <script src="{% static 'js/jquery-3.5.1.min.js' %}" ></script>
        <script src="{% static 'js/bootstrap.min.js' %}" ></script>
        {% block my_js %}{% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% url 'menus:add-ingredient' as add_ingredient %}
    {% url 'menus:list-ingredient' as list_ingredient %}
    {% url 'menus:add-menu' as add_menu %}
    {% url 'menus:list-menu' as list_menu %}

    <div class="row">
        <div class="col-lg-12 form-group">
            <div class="panel panel-success">
                <div class="panel-heading">Ingredients</div>
                <div class="panel-body">
                    <a href="{{add_ingredient}}" class="btn btn-info">Add ingredient</a>
                    <a href="{{list_ingredient}}" class="btn btn-info">Ingredient list</a>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">Menu</div>
                <div class="panel-body">
                    <a href="{{add_menu}}" class="btn btn-info">Create menu</a>
                    <a href="{{list_menu}}" class="btn btn-info">Menu list</a>
                </div>
            </div>

            <div class="panel panel-primary">
                <div class="panel-heading">Preferences</div>
                <div class="panel-body">
                    <a href="#" class="btn btn-info">Look preferences of the employees</a>
                </div>
            </div>

        </div>
        <div class="col-lg-12 form-group">
            <div class="panel panel-danger">
                <div class="panel-heading">Notificacions</div>
                <div class="panel-body">
                    <a href="#" class="btn btn-success">Send message notification by <strong>Whatsapp</strong></a>
                    <a href="#" class="btn btn-success">Send message notification by <strong>Slack</strong></a>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h4 class="text-center">{{message}}</h4>
        </div>
    </div>
{% endblock%}

templates/messages.html
<div class="row">
    <div class="col">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

templates/nav.html
{% url 'login' as login %}
{% url 'logout' as logout %}
{% url 'home' as home %}
{% url 'employees:search-employee' as search_employee %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Menu</a>
            <ul class="nav navbar-nav navbar-left">
                <!-- class="active" -->
                <li><a href="{{search_employee}}">Employees</a></li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{{home}}">Home</a></li>
                    <li><a href="{{logout}}">Logout</a></li>
                {% else %}
                    <li><a href="{{login}}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>