apps/employees/urls.py
# Django
from django.urls import path

# Apps.Employees
from apps.employees import views

app_name='employees'

urlpatterns = [
    path('search/', views.search_employee, name='search-employee'),
    path('list/menu/<int:phone>', views.list_menu, name='list-menu'),
    path('list/plate/<str:identifier>/<int:phone>', views.list_plate_from_menu, name='list-plate-from-menu'),
    path('add/preference/<str:identifier>/<int:phone>/<str:type_plate>', views.add_preference_of_employee, name='add-preference-of-employee'),
]

mi_cornershop/urls.py
#Django
from django.contrib import admin
from django.urls import path, include

#Project
from mi_cornershop import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('users/login', views.login_custom, name='login'),
    path('users/logout', views.logout_custom, name='logout'),
    path('menus/', include('apps.menus.urls')),
    path('employees/', include('apps.employees.urls')),
]

apps/employees/models.py
# Django
from django.db import models

#Apps.menus
from apps.menus import models as views_menu

#Apps.employees
from apps.employees import utils

class Employee(models.Model):
    name = models.CharField(max_length=100, null=False, default='')
    phone = models.IntegerField(null=False, default=0) # wsp
    email = models.EmailField(max_length=254, null=False, default='') # email from account slack
    nationality = models.CharField(max_length=3, default='46', choices=utils.nationality)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

    def get_or_create_plate(self, type_plate):
        """

        :param type_plate (string):
        :return (Plate):
        """
        if not EmployeePreferences.objects.filter(employee=self, plate__type=type_plate).count():
            return views_menu.Plate.objects.create(name=' ', type=type_plate)
        else:
            return EmployeePreferences.objects.filter(employee=self, plate__type=type_plate).first().plate

class EmployeePreferences(models.Model):
    type_options = (
        ('1', 'Like'),
        ('2', 'Hate'),
    )
    type = models.CharField(max_length=1, choices=type_options, default='1')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    plate = models.ForeignKey(views_menu.Plate, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(views_menu.Ingredient, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['plate', 'ingredient']]

"""
Tips to load data: 

** You can use this command for load data 
$ python3 manage.py loaddata employees_06112020.json.json
"""

apps/employees/forms.py
# Django
from django import forms

# Apps.employees
from apps.employees import models

class EmployeePreferencesForm(forms.ModelForm):
    class Meta:
        model = models.EmployeePreferences
        exclude = ('create_at', )
        fields = ('type', 'employee', 'plate', 'ingredient',)
        labels = {
            'type' : 'Preference',
            'ingredient' : 'Ingredient',
        }
        widgets = {
            'type': forms.Select(attrs={'class': 'form-control'}),
            'employee': forms.HiddenInput(),
            'plate': forms.HiddenInput(),
            'ingredient': forms.Select(attrs={'class': 'form-control'}),
        }

apps/employees/views.py
# Django
from django.shortcuts import render, redirect
from django.contrib import messages

# Apps.employees
from apps.employees import models
from apps.employees import forms

# Apps.menus
from apps.menus import models as models_menu

def search_employee(request):
    """

    :param request (POST/GET):
    :return:
    """
    data = dict()

    if request.method == 'POST':
        if 'number' in request.POST:
            if models.Employee.objects.filter(phone=int(request.POST['number'])).exists():
                return redirect('employees:list-menu', int(request.POST['number']) )

    data['title'] = "My prefences"

    return render(request, 'employees/search_employee.html', data)


def list_menu(request, phone):
    """
    Function for lists the menus
    :param request ():
    :param phone (int):
    :return ():
    """

    data = dict()
    my_employe = models.Employee.objects.filter(phone=int(phone))
    if my_employe.count() != 0:
        data['list_menus'] = models_menu.Menu.objects.all()
        data['title'] = 'Menu List'
        data['phone_employee'] = my_employe[0].phone
        data['email_employee'] = my_employe[0].email
    else:
        return redirect('employees:search-employee')

    return render(request, 'employees/menu/list_menu.html', data)

def list_plate_from_menu(request, identifier, phone):
    """

    :param request ():
    :param identifier (str):
    :param phone (int):
    :return:
    """
    data = dict()

    my_plates = models_menu.PlateIngredients.objects.filter(menu__identifier=identifier)
    my_employe = models.Employee.objects.filter(phone=int(phone))

    if my_plates.count()!=0 and my_employe.count()!=0:

        # menu data
        data['my_plates_lunch'] = my_plates.filter(plate__type='1')
        data['my_plates_salad'] = my_plates.filter(plate__type='2')
        data['my_plates_dessert'] = my_plates.filter(plate__type='3')

        # preference data
        my_preference = models.EmployeePreferences.objects.filter(employee__phone=phone)
        if my_preference.count()!=0:
            data['my_prefence_lunch'] = my_preference.filter(plate__type='1')
            data['my_prefence_salad'] = my_preference.filter(plate__type='2')
            data['my_prefence_dessert'] = my_preference.filter(plate__type='3')

        data['title'] = "Menu's plates"
        data['identifier'] = identifier
        data['phone'] = phone
        data['menu'] = my_plates[0].menu

    else:
        return redirect('employees:list-menu', phone)

    return render(request, 'employees/plate/list_plate_from_menu.html', data)

def add_preference_of_employee(request, identifier, phone, type_plate):
    """

    :param request (GET/POST):
    :param identifier (str):
    :param phone (int):
    :return ():
    """

    data = dict()

    if request.method == 'POST':
        form = forms.EmployeePreferencesForm(request.POST)

        if form.is_valid():
            form.save()

            # I send a success message
            messages.success(request, 'Ingredient was add to the preference')

            return redirect('employees:list-plate-from-menu', identifier, phone)
    else:
        form = forms.EmployeePreferencesForm()

        my_employe = models.Employee.objects.filter(phone=int(phone))
        my_plate = my_employe[0].get_or_create_plate(type_plate)

        form.fields['plate'].initial = my_plate
        form.fields['employee'].initial = my_employe[0]

    data['form'] = form
    data['title'] = 'Add preference of employee'
    data['identifier'] = identifier
    data['phone'] = phone
    data['type_plate'] = type_plate

    return render(request, 'employees/plate/add_preference_of_employee.html', data)

apps/employees/templates/employees/plate/add_preference_of_employee.html
{% extends 'base.html' %}

{% block content %}
    {% url 'employees:list-plate-from-menu' identifier phone as back_to_menu %}
    {% url 'employees:add-preference-of-employee' identifier phone type_plate as add_preference %}

    <div class="row">
        <div class="col-lg-1 col-lg-offset-11">
            <a href="{{back_to_menu}}" class="btn btn-info">Back</a>
        </div>
        <div class="col-lg-12">
            <form method="post" id="id_form" name="form" action="{{add_preference}}">
                <div class="form-group">
                    {% csrf_token %}
                    {{form.as_table}}
                </div>
                <div class="form-group">
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button type="submit" class="btn btn-success" id="id_btn_add" name="btn_add">Add</button>
                </div>
            </form>
        </div>
    </div>
{% endblock%}

apps/employees/templates/employees/plate/list_plate_from_menu.html
{% extends 'base.html' %}

{% block content %}
    {% url 'employees:list-menu' phone as list_menu %}

    <div class="row">
        <div class="col-lg-1 col-lg-offset-11">
            <a href="{{list_menu}}" class="btn btn-info">Back</a>
        </div>
    </div>
    <div class="row">
         <div class="panel panel-success">
             <div class="panel-heading">Menu: <strong>{{ menu.name|capfirst }}</strong> /  Date: <strong>{{menu.day|date:"d-m-Y" }}</strong></div>
             <div class="panel-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-lg-4"><h3 style="margin-top: 0px;">Lunch</h3></div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Ingredient</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pi in my_plates_lunch %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ pi.ingredient.name|capfirst }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="2">without ingredients</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-lg-4"><h3 style="margin-top: 0px;">Salad</h3></div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Ingredient</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pi in my_plates_salad %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ pi.ingredient.name|capfirst }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="2">without ingredients</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-4"><h3 style="margin-top: 0px;">Dessert</h3></div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Ingredient</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pi in my_plates_dessert %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ pi.ingredient.name|capfirst }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="2">without ingredients</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
                </div>
            </div>
        </div>


        <div class="panel panel-primary">
            <div class="panel-heading">My preferences</div>
            <div class="panel-body">
                <div class="row">
                    {# LUNCH #}
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-lg-4"><h3 style="margin-top: 0px;">Lunch</h3></div>
                            <div class="col-lg-4 col-lg-offset-3">
                                <a href="{% url 'employees:add-preference-of-employee' identifier phone '1' %}" class="btn btn-primary">Add preference</a>
                            </div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Ingredient</th>
                                    <th>Preference</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pi in my_prefence_lunch %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ pi.ingredient.name|capfirst }}</td>
                                        <td>{{ pi.get_type_display }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="3">without ingredients</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {# SALAD #}
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-lg-4"><h3 style="margin-top: 0px;">Salad</h3></div>
                            <div class="col-lg-4 col-lg-offset-3">
                                <a href="{% url 'employees:add-preference-of-employee' identifier phone '2' %}" class="btn btn-primary">Add preference</a>
                            </div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Ingredient</th>
                                    <th>Preference</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pi in my_prefence_salad %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ pi.ingredient.name|capfirst }}</td>
                                        <td>{{ pi.get_type_display }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="3">without ingredients</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {# DESSERT #}
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-lg-4"><h3 style="margin-top: 0px;">Dessert</h3></div>
                            <div class="col-lg-4 col-lg-offset-3">
                                <a href="{% url 'employees:add-preference-of-employee' identifier phone '3' %}" class="btn btn-primary">Add preference</a>
                            </div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Ingredient</th>
                                    <th>Preference</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pi in my_prefence_dessert %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ pi.ingredient.name|capfirst }}</td>
                                        <td>{{ pi.get_type_display }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="3">without ingredients</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock%}